<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-20T10:52:05 IST" name="Default suite" finished-at="2022-11-20T10:52:13 IST" duration-ms="7580">
    <groups>
    </groups>
    <test started-at="2022-11-20T10:52:05 IST" name="Default test" finished-at="2022-11-20T10:52:13 IST" duration-ms="7580">
      <class name="Screenshot">
        <test-method signature="testBStackTakeScreenShot()[pri:0, instance:Screenshot@355ce81c]" started-at="2022-11-20T10:52:05 IST" name="testBStackTakeScreenShot" finished-at="2022-11-20T10:52:13 IST" duration-ms="7527" status="FAIL">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Destination 'C:\Users\KARTIK'S\git\kartik_cicd_pract\screenshot' exists but is a directory]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Destination 'C:\Users\KARTIK'S\git\kartik_cicd_pract\screenshot' exists but is a directory
at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:665)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:652)
at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:606)
at Screenshot.takeSnapShot(Screenshot.java:37)
at Screenshot.testBStackTakeScreenShot(Screenshot.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBStackTakeScreenShot -->
      </class> <!-- Screenshot -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
